### ISSUE TITLE
Minor problems & Plugin Support [WIP]

### ISSUE THREAD

**Issue by ful1e5** [projekt0n/github-nvim-theme#16]
### Problems

- [x] folds are too bright in dark mode (almost white)
- [x] in Neogit the grey background is a bit too bright
- [x] the window separators are hard to see
- [x] nvim-bufferline with slant separator_style: the slant gets drawn in "white" though I think it should be "grey" as the remaining space in the bufferline.
- [x] [Reddit post](https://www.reddit.com/r/neovim/comments/ogpvwa/github_theme_for_neovim_kitty_and_alacritty_ft_lua/h4kk1zz?utm_source=share&utm_medium=web2x&context=3)

### Plugin Support
- [x] [neogit](https://github.com/TimUntersberger/neogit)
- [x] [vim-gitgutter](https://github.com/airblade/vim-gitgutter)
- [x] [Indent Blankline](https://github.com/lukas-reineke/indent-blankline.nvim)
- [x] [dashboard-nvim](https://github.com/glepnir/dashboard-nvim)
- [x] [which-key.nvim](https://github.com/folke/which-key.nvim/)
- [x] [lspsaga.nvim](https://github.com/glepnir/lspsaga.nvim)
- [x] [nvim-bufferline.lua](https://github.com/akinsho/nvim-bufferline.lua)
- [x] [ALE](https://github.com/dense-analysis/ale)

### TODO:

- [x] Init
- [x] Dynamic theme for `lualine`
- [x] Ask for using github-vscode-theme branding logo (primer/github-vscode-theme#186)
- [x] Support highlight for almost every language.
- [x] Previews & Customization docs inside README.md
- [x] Better color grouping inside [colors.lua](./lua/github-theme/colors.lua)
- [x] Follow [Primer color system](https://primer.style/css/support/color-system)
- [x] Change NvimTreeIcon & DevIcons colors
- [x] Add Github Light Classic & Github Dark Classic styles
- [x] Update Screenshots
